### ISSUE TITLE
SPLICE_COUNTS_DIR using DROP reference data

### ISSUE THREAD

**Issue by Jakob37** [genomic-medicine-sweden/tomte#139]
### Description of the bug

Retrieving one of the DROP datasets from here: https://github.com/gagneurlab/drop (https://zenodo.org/records/6078397), the pipeline crashes in a setup step.

It looks like a column`SPLICE_COUNTS_DIR` is missing from the provided `sampleAnnotation.tsv` file.

Looking in the test data, it seems to simply be the name of the folder.

I'll test adding this to the downloaded annotation. Wondering if this could be handled in some other way though. Either if this dir value could be derived from the DROP reference folder (already provided through the params), or provided through a different setting, such that we don't need to edit the reference data.

### Command used and terminal output

```console
Error:


-[genomic-medicine-sweden/tomte] Pipeline completed with errors-
ERROR ~ Error executing process > 'GENOMICMEDICINESWEDEN_TOMTE:TOMTE:ANALYSE_TRANSCRIPTS:DROP_SAMPLE_ANNOT (DROP_sample_annot)'

Caused by:
  Process `GENOMICMEDICINESWEDEN_TOMTE:TOMTE:ANALYSE_TRANSCRIPTS:DROP_SAMPLE_ANNOT (DROP_sample_annot)` terminated with an error exit status (1)


Command executed:

  /fs1/jakob/src/tomte/bin/drop_sample_annot.py \
      --bam sample_id.Aligned.sortedByCoord.out.bam \
      --samples sample_id \
      --strandedness reverse \
      --single_end false \
      --ref_count_file geneCounts.tsv.gz \
      --ref_annot sampleAnnotation.tsv \
      --drop_group_sample outrider,fraser \
      --output sample_annotation.tsv
  
  cat <<-END_VERSIONS > versions.yml
  "GENOMICMEDICINESWEDEN_TOMTE:TOMTE:ANALYSE_TRANSCRIPTS:DROP_SAMPLE_ANNOT":
      drop_sample_annot: $($baseDir/bin/drop_sample_annot --version )
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3790, in get_loc
      return self._engine.get_loc(casted_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
    File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
    File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
  KeyError: 'SPLICE_COUNTS_DIR'
  
  The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
    File "/fs1/jakob/src/tomte/bin/drop_sample_annot.py", line 108, in <module>
      main()
    File "/fs1/jakob/src/tomte/bin/drop_sample_annot.py", line 104, in main
      write_final_annot_to_tsv(ref_count_file=args.ref_count_file, ref_annot=args.ref_annot, out_file=args.output)
    File "/fs1/jakob/src/tomte/bin/drop_sample_annot.py", line 61, in write_final_annot_to_tsv
      df_reference["SPLICE_COUNTS_DIR"] = df_reference["SPLICE_COUNTS_DIR"].str.rstrip("/").apply(os.path.basename)
                                          ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/site-packages/pandas/core/frame.py", line 3896, in __getitem__
      indexer = self.columns.get_loc(key)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3797, in get_loc
      raise KeyError(key) from err
  KeyError: 'SPLICE_COUNTS_DIR'

Work dir:
  /<work base>/tomte/09/b80159e6ffc20ede0cf13e228b90ed

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
ERROR ~ Pipeline failed. Please refer to troubleshooting docs: https://nf-co.re/docs/usage/troubleshooting

 -- Check '.nextflow.log' file for details
```
```


### Relevant files

_No response_

### System information

_No response_

**Comment by Jakob37** [comment]
Looking closer, I realize that there is a bunch of settings to add to the annotation file.

Maybe not a bug then. But might be helpful with brief instructions guiding the user through it.

I am using a script like this to add the columns:

```
#!/bin/bash

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <orig tsv>"
    exit 1
fi

orig_tsv=$1

cat ${orig_tsv} |\
    awk 'NR == 1 {print $0"\tSPLICE_COUNTS_DIR"} NR > 1 {print $0"\tWhole_Blood--GRCh38--gencode29"}' |\
    awk 'NR == 1 {print $0"\tDROP_GROUP"} NR > 1 {print $0"\toutrider, fraser"}' |\
    awk 'NR == 1 {print $0"\tCOUNT_OVERLAPS"} NR > 1 {print $0"\tTRUE"}' |\
    awk 'NR == 1 {print $0"\tHPO_TERMS"} NR > 1 {print$0"\tNA"}' |\
    awk 'NR == 1 {print $0"\tCOUNT_MODE"} NR > 1 {print$0"\tIntersectionStrict"}'
```

Closing, as a non-issue!
